Repository btcven/locha-p2p, pull requests merged in 2020-09, with the labels that each got.

#14 Add port mapping
  locha-p2pd/src/main.rs
  miniupnpc/src/lib.rs
  src/network.rs
  src/runtime.rs
  src/runtime/events.rs
  src/upnp.rs
Labels: State: Ready for Review, Type: enhancement

#15 Handle all swarm events on runtime
  locha-p2pd/src/main.rs
  src/runtime.rs
  src/runtime/events.rs
Labels: State: Ready for Review, Type: enhancement

#16 Don't allow shared addresses by default on discovery
  locha-p2pd/src/arguments.rs
  locha-p2pd/src/cli.yml
  locha-p2pd/src/main.rs
  src/discovery.rs
  src/runtime.rs
  src/runtime/config.rs
Labels: State: Ready for Review, Type: bug, Type: enhancement

#18 Add swarm type
  src/lib.rs
  src/runtime.rs
Labels: State: Ready for Review

#17 Better UPnP implementation
  locha-p2pd/Cargo.toml
  locha-p2pd/src/main.rs
  miniupnpc/src/lib.rs
  src/discovery.rs
  src/lib.rs
  src/runtime.rs
  src/runtime/config.rs
  src/runtime/sync_start_cond.rs
  src/upnp.rs
Labels: State: Ready for Review, Type: enhancement

#20 Resolve external addresses using UPnP
  Cargo.toml
  locha-p2pd/src/main.rs
  src/lib.rs
  src/network.rs
  src/runtime.rs
  src/upnp.rs
Labels: State: Ready for Review, Type: enhancement

#21 Add function to get PeerId
  src/runtime.rs
Labels: State: Ready for Review, Type: enhancement

#23 stale bot, add stale.yml
  .github/stale.yml
Labels: State: Ready for Review, Type: question, help wanted

#24 Add test example for build_swarm
  src/lib.rs
Labels: State: Ready for Review

#25 Make UPnP use only one thread
  locha-p2pd/src/main.rs
  src/network.rs
  src/runtime.rs
  src/upnp.rs
Labels: State: Ready for Review, Type: enhancement

#29 Update libp2p to 0.28
  Cargo.toml
Labels: State: Ready for Review, Type: enhancement

#28 Add code coverage testing with cargo-tarpaulin
  .github/workflows/rust.yml
Labels: Area: CI/CD, Type: enhancement

#31 Add tests for IP addresses validation
  locha-p2pd/src/arguments.rs
  locha-p2pd/src/cli.yml
  locha-p2pd/src/main.rs
  src/discovery.rs
Labels: State: Ready for Review, Type: enhancement

#30 Fix UPnP timer bug
  src/upnp.rs
Labels: State: Ready for Review, Type: bug

#26 Add test example for build_transport
  src/transport.rs
Labels: State: Ready for Review, Type: documentation, Type: enhancement

#32 Add tests for IP address filtering
  src/discovery.rs
Labels: State: Ready for Review, Type: enhancement

#34 Remove echo option from locha-p2pd
  locha-p2pd/Cargo.toml
  locha-p2pd/src/arguments.rs
  locha-p2pd/src/cli.yml
  locha-p2pd/src/main.rs
Labels: State: Ready for Review, Type: enhancement

#33 Initial attempt at bootstrapping
  locha-p2pd/src/arguments.rs
  locha-p2pd/src/cli.yml
  locha-p2pd/src/main.rs
  src/discovery.rs
  src/lib.rs
  src/network.rs
  src/runtime.rs
Labels: State: Ready for Review, Type: enhancement

#35 Implement Kademlia DHT random walking
  locha-p2pd/src/main.rs
  src/discovery.rs
  src/lib.rs
  src/runtime.rs
Labels: State: Ready for Review, Type: enhancement

#39 Fix bootstrap
  locha-p2pd/src/arguments.rs
  locha-p2pd/src/cli.yml
  locha-p2pd/src/main.rs
  src/discovery.rs
  src/runtime.rs
  src/runtime/events.rs
Labels: State: Ready for Review, Type: enhancement

#40 Add found peers to Kademlia routing table
  src/discovery.rs
  src/network.rs
  src/runtime.rs
Labels: State: Ready for Review, Type: enhancement

#41 Remove filtering of IP addresses
  locha-p2pd/src/arguments.rs
  locha-p2pd/src/cli.yml
  locha-p2pd/src/main.rs
  src/discovery.rs
  src/runtime/events.rs
Labels: State: Ready for Review, Type: enhancement

#42 Minimal implementation of libp2p logic
  .github/workflows/rust-musl.yml
  Cargo.toml
  locha-p2pd/Cargo.toml
  locha-p2pd/src/arguments.rs
  locha-p2pd/src/cli.yml
  locha-p2pd/src/main.rs
  src/discovery.rs
  src/lib.rs
  src/network.rs
  src/p2p.rs
  src/p2p/behaviour.rs
  src/p2p/pubsub.rs
  src/runtime.rs
  src/runtime/config.rs
  src/upnp.rs
Labels: State: Ready for Review
